function catMouse(map, moves) {
    let X = Y = xC = yC = xM = ym = animals = 0
    for (let i = 0; i < map.length; i++) {
        console.log(map.indexOf("\n"))
        if (map[i] === "C") {
            xC = X
            yC = Y
            animals++
            // console.log("координаты кошки: ", xC, " x ", yC)
        }
        if (map[i] === "m") {
            xm = X
            ym = Y
            animals++
            // console.log("координаты мышки: ", xm, " x ", ym)
        }
        if (map[i] === "." || map[i] === "C" || map[i] === "m") {
            X++
            if (X === 9) {
                X = 0
                Y++
            }
        }
    }
    if (animals !== 2) {return "boring without two animals"}
    let zap = Math.abs(xC - xm) + Math.abs(yC - ym)
    // console.log(zap)
    if (zap <= moves) {return "Caught!"} else {return "Escaped!"}
}

console.log (catMouse(`...............C..
.n................
...................
..................
..................
..................
..................
..................
..................
..................
..................
..................
..................
..................
..................
..................
..................`, 2))
